name: Demo
on:
  issue_comment:

jobs:
  # only run this workflow if the previous run has completed
  consecutiveness:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.title == 'Demo' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  # some other job
  something:
    runs-on: ubuntu-latest
    needs: [ consecutiveness ]
    steps:
    - run: |
        echo "Previous workflow runs have completed!"
        sleep 60